### ISSUE TITLE
执行 npm install 命令就出错

### ISSUE THREAD

**Issue by rieuse** [MikeCoder/hexo-tag-cloud#10]
然后执行hexo其他操作就有问题了

```
FATAL Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\lib\find_pkg. js:23:25
    at tryCatcher (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Shinelon\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by D0n9X1n** [comment]
我这边没有能复现出来。
能贴一下你的 package.json 还有 _config.yml 以及 `hexo version` 的信息吗？
还有具体操作流程是怎样的？

**Comment by D0n9X1n** [comment]
如果是 `npm install` 就有问题，确保 *package.json* 没问题的情况下多试几次，可能会是网络问题(翻墙或者修改 npm 源都可以)。

**Comment by rieuse** [comment]
网络问题，已解决，谢谢
